import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Header2 from "@/components/Header/Header2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <Header2></Header2>
      
      {children}</body>
    </html>
  );
}
